[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*


markers = 
    ui: Маркировка для UI тестов
    slow: Маркировка для медленных тестов
    smoke: Маркировка для смоук тестов
    critical: Маркировка для критичных тестов
    regression: Маркировка для регрессионных тестов
    registration: Маркировка для тестов, связанных с регистрацией пользователей
    authorization: Маркировка для тестов, связанных с авторизацией пользователей
    courses: Маркировка для тестов, связанных с курсами